version: '3'

services:
  app:
    build:
      context: ./node
    container_name: app
    image: glaucia86/node-desafio-fc:latest
    networks:
      - app-node-network
    volumes:
      - ./node:/usr/src/app
    environment:
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: nodedb
    tty: true
    ports:
      - '3000:3000'
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    image: glaucia86/nginx-desafio-fc:latest
    ports:
      - '8080:80'
    networks:
      - app-node-network
    depends_on:
      - app

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: nodedb
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-node-network

networks:
  app-node-network:
    driver: bridge
